---
nftables_allowed_ports:
  - 80    # HTTP
  - 443   # HTTPS
  
http_port: 80
https_port: 443

nginx_version: "1.28.0"
nginx_src_dir: "/usr/local/src"
brotli_repo: "https://github.com/google/ngx_brotli.git"

web_root: /usr/share/nginx/html
index_file: index.html
server_name: example.com
server_name_ssl: example.com

ssl_cert_path: /etc/nginx/ssl/cert.pem
ssl_key_path: /etc/nginx/ssl/key.pem
ssl_cert_path: "/etc/ssl/certs/nginx-selfsigned.crt"
ssl_key_path: "/etc/ssl/private/nginx-selfsigned.key"
ssl_days_valid: "+365d"