---
- name: Install dan konfigurasi Fail2ban untuk keamanan SSH
  hosts: all
  become: yes
  vars:
    fail2ban_sshd_enabled: true
    fail2ban_maxretry: 5
    fail2ban_bantime: 3600  # Dalam detik (1 jam)
    fail2ban_findtime: 600  # Dalam detik (10 menit)
    fail2ban_ignoreip: "127.0.0.1/8"  # IP yang diabaikan (misalnya, localhost)

  tasks:
    - name: Update daftar paket
      apt:
        update_cache: yes
      when: ansible_pkg_mgr == "apt"

    - name: Install Fail2ban
      apt:
        name: fail2ban
        state: present
      when: ansible_pkg_mgr == "apt"

    - name: Buat konfigurasi jail.local untuk Fail2ban
      copy:
        content: |
          [DEFAULT]
          ignoreip = {{ fail2ban_ignoreip }}
          bantime = {{ fail2ban_bantime }}
          findtime = {{ fail2ban_findtime }}
          maxretry = {{ fail2ban_maxretry }}

          [sshd]
          enabled = {{ fail2ban_sshd_enabled | bool | lower }}
          port = ssh
          logpath = %(sshd_log)s
           backend = %(sshd_backend)s
        dest: /etc/fail2ban/jail.local
        owner: root
        group: root
        mode: '0644'
      notify: Restart Fail2ban

    - name: Nonaktifkan autentikasi kata sandi SSH
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication no'
        state: present
      notify: Restart SSH

    - name: Nonaktifkan login root melalui SSH
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin no'
        state: present
      notify: Restart SSH

    - name: Pastikan service Fail2ban aktif dan berjalan
      systemd:
        name: fail2ban
        enabled: yes
        state: started

  handlers:
    - name: Restart Fail2ban
      systemd:
        name: fail2ban
        state: restarted

    - name: Restart SSH
      systemd:
        name: ssh
        state: restarted